name: 'InfraDeployment-VMNetwork'

trigger:
  batch: true
  branches: 
    include: 
      - main
    exclude: 
      - feature

pool:
  name: Default

steps:
- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'
- template: templatesteppipelines.yml

- task: TerraformTaskV4@4
  inputs:
    provider: 'azurerm'
    command: 'plan'
    environmentServiceNameAzureRM: 'azure-devopsrc'

