name: 'InfraDeployment-VMNetwork'

trigger:
  batch: true
  branches: 
    include: 
      - main
    exclude: 
      - feature

pool:
  name: Default

steps:
- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'

- task: TerraformTaskV4@4
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'azure-devopsrc'
    backendAzureRmResourceGroupName: 'DoNotDelete-pipeline'
    backendAzureRmStorageAccountName: 'storageaccountdevops'
    backendAzureRmContainerName: 'container-devops'
    backendAzureRmKey: 'dev.terraform.tfstate'

- task: TerraformTaskV4@4
  inputs:
    provider: 'azurerm'
    command: 'plan'
    environmentServiceNameAzureRM: 'azure-devopsrc'

